# Generated by Django 5.1.6 on 2025-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
